services:
  - type: web
    name: orientation-day-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && node prisma/seedAdmin.js && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_VsUkyHo34JNA@ep-crimson-glade-axgzv03m.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 12h
      - key: DEFAULT_ADMIN_USERNAME
        value: admin@orientation.edu
      - key: DEFAULT_ADMIN_PASSWORD
        value: admin-2026
      - key: DEFAULT_ADMIN_NAME
        value: Orientation Admin
